version: "3.7"

services:
    fpm:
        image: php:8.0-fpm
        volumes:
            - .:/var/www
    nginx:
        image: nginx:1.21.3
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/templates/default.conf.template
            - ./storage/logs/nginx:/var/log/nginx
            - .:/var/www
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
